sudo: false

language: node_js

node_js:
  - "7"
  - "6"

before_script:
  - npm install

script:
  - npm run test
  - istanbul cover ./node_modules/mocha/bin/_mocha output/tests --report lcovonly -- -R spec && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
